add_newline = true

format = '''
[\[$directory\]](bright-white)$kubernetes$git_status$git_branch
$env_var$character'''

[env_var.PROMPT_EXTRA]
style = 'purple'
variable = 'PROMPT_EXTRA'
format = '[ $env_value]($style)'

[kubernetes]
style = 'green'
symbol = ''
format = ' [\[[$symbol$context([/](bright-white)$namespace)]($style)\]](bright-white)'
disabled = false

[[kubernetes.contexts]]
context_pattern = '.*sandbox.*'
context_alias = 'sb'

[[kubernetes.contexts]]
context_pattern = '.*dev.*'
context_alias = 'dev'

[[kubernetes.contexts]]
context_pattern = '.*test.*'
context_alias = 'test'

[[kubernetes.contexts]]
context_pattern = '.*prod.*'
context_alias = 'prod'
style = 'red'

[directory]
style = 'blue'
format = '[$path]($style)'
truncate_to_repo = true

[git_status]
style = 'red'
deleted = 'x'
diverged = '[⇡⇣](purple)'
format = ' [\[[$all_status$ahead_behind]($style)](bright-white)'

[git_branch]
style = 'yellow'
symbol = ''
format = '[[$branch]($style)\]](bright-white)'

[character]
success_symbol = ' [->](white)'
error_symbol = ' [|>](red)'
