[language-server]
jdtls = { command = "jdtls", args = ["--jvm-arg=-javaagent:/home/thomas/.config/helix/java/lombok-1.18.32.jar"] }
omnisharp = { command = "omnisharp", args = ["--languageserver"] }
yaml = { command = "yaml-language-server", args = ["--stdio"], config = { yaml = { format = { enable = true }, keyOrdering = true } } } # https://github.com/redhat-developer/yaml-language-server#language-server-settings
none = { command = "" }

[[language]]
name = "bash"
language-servers = ["none"]

[[language]]
name = "c-sharp"
language-servers = ["omnisharp"]

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "python"
auto-format = true
indent = { tab-width = 4, unit = "	" }
formatter = { command = "black", args = ["-", "-l160"]}

[[language]]
name = "typescript"
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }

[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
language-servers = ["yaml"]
auto-format = false
formatter = { command = "prettier", args = ["--parser", "yaml"] }
