[language-server]
omnisharp = { command = "omnisharp", args = [ "--languageserver" ] }
yaml = { command = "yaml-language-server", args = ["--stdio"], config = { yaml = { format = { enable = true }, keyOrdering = true } } } # https://github.com/redhat-developer/yaml-language-server#language-server-settings
none = { command = "" }

[[language]]
name = "python"
auto-format = true
indent = { tab-width = 4, unit = "	" }
formatter = { command = "black", args = ["-", "-l160"]}

[[language]]
name = "c-sharp"
language-servers = ["omnisharp"]

[[language]]
name = "bash"
language-servers = ["none"]

[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
language-servers = ["yaml"]
